server:
  port: 9999
spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ae1a055e-cc74-4875-a3f0-feb15e1714db
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: user-service #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://user-service #匹配后提供服务的路由地址
          predicates:
            - Path=/rst-user/** # 断言，路径相匹配的进行路由

        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/rst-video/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"  #允许所有ip跨域访问
            allowedMethods: "*"  #允许所有请求方式
            allowedHeaders: "*"  #允许任何头进行跨域
            allowCredentials: true #允许携带cookie
            ## 以上配完成，简单跨域复杂跨域都允许。